language: ruby
rvm:
- 2.1.1
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
- cp config/database.yml.travis config/database.yml
- bundle exec rake db:create
- bundle exec rake db:migrate
script:
- bundle exec rake spec
deploy:
  provider: heroku
  api_key:
    secure: YqQ2HUX6LPIuCs48s5wggPQcKk5AwOKilotN4uEqcTUqRyO5kbfDmR5j2slcWyEI9nvN8BjyJpCnYumRXBGlaX6FIHFPH0VlllkrrBfMSV5JpmqGDALOh/M1E+7h8+7h3+JtHEV1Tu317tygVcoawvEOoooEDpTJPZMsHCwkTuU=
  app: calm-basin-9174
  on:
    repo: bebepeng/listen_to
  run:
  - bundle exec rake db:migrate
notifications:
  email: false
env:
  global:
    secure: Y6OBYldneT9VvAcaV6L9KaLzDdbLiiDf03y72y9Xz+BZAIEVb97dmaNzl1jWDCZfaQbhkaAgOJfmyp1gT45o76NSC5GrOC688Hm7rilO+/nMi+mn51uEGedk2DNHPZEedpmQRl7sKVEnezuhh02130t0gq0kUJTqUOFLBUX/fTQ=
